services:
  - type: pserv
    name: datadog-agent
    runtime: docker
    plan: starter
    envVars:
      - key: DD_API_KEY
        sync: false
      - key: DD_POSTGRES_HOST
        sync: false
      - key: DD_POSTGRES_USER
        sync: false
      - key: DD_POSTGRES_PASSWORD
        sync: false
